# Generated by Django 3.2.9 on 2021-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0002_auto_20211201_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='common_recipes',
            field=models.ManyToManyField(to='main.Recipe'),
        ),
    ]
