# Generated by Django 3.2.9 on 2021-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoon_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('ready_minutes', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('summary', models.TextField()),
                ('instructions', models.TextField()),
                ('ingredients', models.ManyToManyField(to='main.Ingredient')),
            ],
        ),
    ]
